#!/usr/bin/python3
import os.path

import OpenSSL.crypto


CERT_FILE = "/srv/tls/certs/full.pem"

# Create a key pair
k = OpenSSL.crypto.PKey()
k.generate_key(OpenSSL.crypto.TYPE_RSA, 4096)

# Create a self-signed certificate
cert = OpenSSL.crypto.X509()
cert.get_subject().CN = "example.com"
cert.set_serial_number(1)
cert.gmtime_adj_notBefore(0)
cert.gmtime_adj_notAfter(-1800)
cert.set_issuer(cert.get_subject())
cert.set_pubkey(k)
cert.sign(k, "sha256")

os.makedirs(os.path.dirname(CERT_FILE), exist_ok=True)

with open(CERT_FILE, "wb") as f:
    f.write(OpenSSL.crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, k))
    f.write(OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, cert))
